package com.blog.api.configuration;

public class JwtConstant {

	public static final String SECURITY_KEY = "wdkljfbejkfhjfhejkfenfnhgfjew;nflnfjebfiehfjef;enfjkwbejfwbfjnejfbewfbweklfnjgnblmvnjgnrjgbrjignbjoirhbgjrnogjhrognrjghrgnjkhgorhgjkhgorkgnrjognjgorngodknoeegnjdfmgepmlreopdjokgmepghethngtemgeoktngjtrgsdhufidufjsdjfhsidjfnsd47634736434kbjsdfbdfjb";

	public static final String SECURITY_HEADER = "Authorization";
}
